version: "3.12"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis

  celery:
    build: .
    command: poetry run celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
      - mongodb

  redis:
    image: "redis:alpine"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
