"""Initial migration

Revision ID: 2053ac45a8f5
Revises: 
Create Date: 2024-10-01 21:14:15.538971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2053ac45a8f5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "houses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_houses_address"), "houses", ["address"], unique=False)
    op.create_index(op.f("ix_houses_id"), "houses", ["id"], unique=False)
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("price_per_square_meter", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tariffs_id"), "tariffs", ["id"], unique=False)
    op.create_index(op.f("ix_tariffs_name"), "tariffs", ["name"], unique=False)
    op.create_table(
        "apartments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column("house_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apartments_id"), "apartments", ["id"], unique=False)
    op.create_table(
        "meters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("readings", sa.String(), nullable=True),
        sa.Column("apartment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meters_id"), "meters", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meters_id"), table_name="meters")
    op.drop_table("meters")
    op.drop_index(op.f("ix_apartments_id"), table_name="apartments")
    op.drop_table("apartments")
    op.drop_index(op.f("ix_tariffs_name"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_id"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index(op.f("ix_houses_id"), table_name="houses")
    op.drop_index(op.f("ix_houses_address"), table_name="houses")
    op.drop_table("houses")
    # ### end Alembic commands ###
